sudo: false
language: generic

cache: apt

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libudev-dev
            - libjpeg8-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libudev-dev
            - libjpeg8-dev
            - libx11-xcb-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: *sources

before_script :
  - mkdir build
  - cd build

script:
  - cmake -G"Unix Makefiles" ..
  - make
