sudo: false
language: generic

cache:
  apt: true
  directories:
    - /tmp/tools

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libudev-dev
            - libjpeg8-dev
            - libopenal-dev
            - libx11-xcb-dev
            - libsndfile1-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libudev-dev
            - libjpeg8-dev
            - libopenal-dev
            - libx11-xcb-dev
            - libsndfile1-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
          sources: *sources
    - os: osx
      language: cpp
      compiler: gcc
    - os: osx
      language: cpp
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="$HOME/bin:$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir -p ~/bin /tmp/tools; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate --no-clobber -O /tmp/tools/cmake https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.sh || true; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod -R +x /tmp/tools; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /tmp/tools/cmake --prefix="$HOME" --exclude-subdir; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cmake || brew upgrade cmake; fi

before_script :
  - mkdir build
  - cd build

script:
  - cmake -G"Unix Makefiles" ..
  - make mandalas
